config/routes.rb
Rails.application.routes.draw do
  resources :brands, except: [:index] do
    resources :yarns, only: [:index, :new]
  end

  resources :tools, except: [:show]

  resources :yarns, except: [:show]

  resources :projects do
    resources :yarns, only: [:index]
    resources :tools, only: [:index, :new]
  end

  resources :finish_projects, only: [:edit, :update]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

  root 'application#home'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy
  has_many :tools
  has_many :yarns
  has_many :brands, -> { distinct }, through: :yarns

  accepts_nested_attributes_for :notes, reject_if: :all_blank

  validates_presence_of :name, :status
  validates_uniqueness_of :name, scope: :user_id

  scope :wip, -> { where(status: "In Progress") }
  scope :upcoming, -> { where(status: "Upcoming") }
  scope :finished, -> { where(status: "Finished") }

  def note_attributes=(attributes)
     note = Note.find_or_create_by(note: attributes[:note], project_id: self.id)
     note.update(attributes)
  end

  def yarns_attributes=(yarns_attributes)
    yarns_attributes.values.each do |attributes|
      yarn = Yarn.find(attributes[:id])
      yarn.update(attributes)
    end
  end

  def project_yarns_by_color
    yarns.ordered_by_color
  end

  def yarns_by_brand
    self.project_yarns_by_color.includes(:brand).order('brands.name')
  end

  def clear_to_stash
    self.tools.each do |tool|
      tool.project = self.user.stash
      tool.save
    end

    self.yarns.each do |yarn|
      if !yarn.count || yarn.count <= 0
        if yarn.scrap.empty? || yarn.scrap.to_f == 0.0
          yarn.destroy
        end
      else
        yarn.project = self.user.stash
        yarn.save
      end
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :auth_user, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects
    respond_to do |f|
      f.html
      f.json {render json: @projects}
    end
  end

  def show
    respond_to do |f|
      f.html
      f.json {render json: @project}
    end
  end

  def new
    @project = Project.new
    @project.notes.build
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      # redirect_to project_path(@project)
      render json: @project
    else
      @project.notes.build
      render :new
    end
  end

  def edit
    @project.notes.build
  end

  def update
    if @project.update(project_params)
      if @project.status == "Finished"
        if !@project.yarns.empty?
          render "finish_projects/edit"
        else
          @project.clear_to_stash
          redirect_to project_path(@project)
        end
      else
        redirect_to project_path(@project)
      end
    else
      render :edit
    end
  end

  def destroy
    @project.clear_to_stash
    @project.destroy
    @projects = current_user.projects
    respond_to do |f|
      f.html
      f.json {render json: @projects}
    end
    redirect_to projects_path
  end

  private
    def find_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :status, :pattern_info, notes_attributes: [:note], yarn_ids:[], tool_ids:[])
    end

    def auth_user
      if current_user == @project.user
      else
        flash['error'] = "You are not allowed to view or edit another users project."
        redirect_to root_path
      end
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def status_choices
    ['In Progress', 'Upcoming', 'Finished']
  end

end

app/views/projects/_all.html.erb
<div class="inside">
  <h1>Projects</h1>

  <div class="list-project status-constant">
    <div>
      <h2><%= link_to current_user.stash.name, project_path(current_user.stash) %></h2>
    </div>
  </div>

  <% if !current_user.projects.wip.empty? %>
    <div class="list-project status-in-progress">
      <h2>In Progress:</h2>
        <% current_user.projects.wip.each do |project| %>
        <div class="each-project">
          <%= link_to project.name, project_path(project) %>
        </div>
        <% end %>
      </div>
  <% end %>

<% if !current_user.projects.upcoming.empty? %>
  <div class="list-project status-upcoming">
    <h2>Upcoming:</h2>
      <% current_user.projects.upcoming.each do |project| %>
      <div class="each-project">
        <%= link_to project.name, project_path(project) %>
      </div>
      <% end %>
    </div>
  <% end %>

<% if !current_user.projects.finished.empty? %>
  <div class="list-project status-finished">
    <h2>Finished:</h2>
      <% current_user.projects.finished.each do |project| %>
      <div class="each-project">
        <%= link_to project.name, project_path(project) %>
      </div>
      <% end %>
      </div>
  <% end %>
</div>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@project.errors.count, "error") %>
      prohibited this project from being saved:
    </h2>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @project do |f| %>
<% if @project != current_user.stash %>
  <fieldset>
    <legend>Project:</legend>
    <div class="field<%= ' field_with_errors' if @project.errors[:name].any? %>">
      <%= f.label "Name:" %>
      <%= f.text_field :name %><br>
    </div>

    <div class="field<%= ' field_with_errors' if @project.errors[:status].any? %>">
      <%= f.select :status, status_choices, :prompt => 'Select Status' %>
    </div>

    <div>
      <%= f.label "Pattern:" %>
      <%= f.text_field :pattern_info %>
    </div>


    <div>
      <%= f.fields_for :notes do |n| %>
      <div>
        <% if @project.notes.first.note && n.object.note %>
            <p><em><%= n.object.created_at.localtime.strftime("%m/%d/%Y, %l:%M %p") unless !n.object.created_at %></em></p>
            <p><%= n.object.note unless !n.object.created_at %></p>
        <% else  %>
      </div>


        <div class="field<%= ' field_with_errors' if n.object.errors[:note].any? %>">
          <%= n.label "Note:" %><br>
          <%= n.text_area :note %>
        </div>
        <% end %>
      <% end %>
    </div>
  </fieldset>
<% end %>

<fieldset>
  <legend>Select Yarn:</legend>
  <div class="checkbox_container">
    <%= f.collection_check_boxes(:yarn_ids, current_user.yarns_sorted_by_brand, :id, :brand_yarn_with_project) %>
  </div>
</fieldset>

<fieldset class="check_box">
  <legend>Select Tools:</legend>
  <div class="checkbox_container">
    <%= f.collection_check_boxes(:tool_ids, current_user.tools, :id, :tool_with_project) %>
  </div>
</fieldset>

  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<div class="inside">
  <h1>Edit <%= @project.name %></h1>

  <%= render "form" %>
</div>

app/views/projects/new.html.erb
<div class="inside">
  <h1>Create a Project</h1>

  <%= render "form" %>
<div>

app/views/projects/show.html.erb
<div class="inside">
  <h1><%= @project.name %></h1>

  <% if @project.name != "Stash" %>
    <div class="project-details">
      <p><b>Status:</b>  <%= @project.status %></p>
      <p><b>Pattern:</b>  <%= @project.pattern_info %></p>
    </div>
  <% end %>

  <% if !@project.notes.empty? %>
  <div class="project-notes">
    <h2>Notes:</h2>
    <div>
      <% @project.notes.each do |note| %>
        <div class="each-note">
          <p><em><%= note.created_at.localtime.strftime("%m/%d/%Y, %l:%M %p") %></em></p>
          <p><%= note.note %></p>
        </div>
      <% end %>
    </div>
  </div>
  <% end %>

  <% if !@project.yarns.empty? %>
  <div class="project-yarns">
    <% if @project.name != "Stash" %>
      <h2>Project Yarn:</h2>
    <% else %>
      <h2>Stashed Yarn:</h2>
    <% end %>
    <ul class="project-yarn-list">
      <% @project.yarns_by_brand.each do |yarn| %>
        <li class="each-project-yarn"><%= brand_yarn_links yarn %> <span class="yarn-details"><%= yarn_amount yarn %></span></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <% if !@project.tools.empty? %>
  <div class="project-tools">
    <% if @project.name != "Stash" %>
      <h2><%= link_to "Project Tools:", project_tools_path(@project) %></h2>
    <% else %>
      <h2><%= link_to "Stashed Tools:", project_tools_path(@project) %></h2>
    <% end %>
    <ul class="project-tool-list">
      <% @project.tools.each do |tool| %>
        <li class="each-project-tool"><%= link_to tool.name, edit_tool_path(tool) %></li>
      <% end %>
    </ul>
    <%= link_to "Add a tool to this project", new_project_tool_path(@project) %>
  </div>
  <% end %>

    <%= button_to "Edit Project", edit_project_path(@project), method: :get %>
  <% if @project != current_user.stash %>
    <%= button_to "Delete Project", { action: "destroy", id: @project.id }, method: :delete, data: { confirm: "This will move all associated yarn and tools to your Stash. Are you sure you'd like to frog this project?" } %>
  <% end %>
</div>