config/routes.rb
Rails.application.routes.draw do
  resources :brands, except: [:index] do
    resources :yarns, only: [:index, :new]
  end

  resources :tools, except: [:show]

  resources :yarns, except: [:show]

  resources :projects do
    resources :yarns, only: [:index]
    resources :tools, only: [:index, :new]
  end

  resources :finish_projects, only: [:edit, :update]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

  root 'application#home'
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :yarns, dependent: :destroy

  validates_presence_of :name

  def yarns_attributes=(yarns_attributes)
    yarns_attributes.values.each do |yarn_attributes|
      if !yarn_attributes[:color].empty?
        if yarn_attributes[:brand_id].empty?
          yarn = self.yarns.build(yarn_attributes)
          yarn.save
        else
          yarn = Yarn.create(yarn_attributes)
        end
      end
    end
  end

  def yarns_by_color
    yarns.ordered_by_color
  end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :find_brand, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @brand = Brand.new
    5.times do
      @brand.yarns.build
    end
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to brand_path(@brand)
    elsif !params[:brand][:skein_weight].empty? || !params[:brand][:skein_length].empty?
      5.times do
        @brand.yarns.build
      end
      render :new
    else
      @yarns = current_user.yarns
      render json: @yarns
      # redirect_to yarns_path
    end
  end

  def edit
  end

  def update
    if @brand.update(brand_params)
      redirect_to brand_path(@brand)
    else
      render :edit
    end
  end

  def destroy
    @brand.destroy
    redirect_to root_path
  end

  private
    def find_brand
      @brand = Brand.find(params[:id])
    end

    def brand_params
      params.require(:brand).permit(
        :name, :material, :weight, :hook, :needle, :skein_weight, :skein_length,
        yarns_attributes: [:color, :count, :scrap, :project_id, :brand_id]
      )
    end

end

app/helpers/brands_helper.rb
module BrandsHelper

  def material_choices
    ['Acrylic', 'Cotton', 'Wool', 'Alpaca', 'Other']
  end

  def weight_choices
    ['0 - Lace', '1 - Super Fine', '2 - Fine', '3 - Light', '4 - Medium', '5 - Bulky', '6 - Super Bulky', '7 - Jumbo', 'Novelty']
  end

end

app/views/brands/_form.html.erb
<% if @brand.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@brand.errors.count, "error") %>
      prohibited this brand from being saved:
    </h2>
    <ul>
    <% @brand.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @brand do |f| %>
<fieldset>
  <legend>Brand:</legend>
  <div class="field<%= ' field_with_errors' if @brand.errors[:name].any? %>">
    <%= f.label "Name:" %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label "Select Material:" %>
    <%= f.select :material, material_choices %>
  </div>

  <div>
    <%= f.label "Select Gauge:" %>
    <%= f.select :weight, weight_choices, :selected => '4 - Medium' %>
  </div>

  <div>
    <%= f.label "Skein weight (oz):" %>
    <%= f.number_field :skein_weight, :class => 'text_field', :step => 0.1 %>
  </div>

  <div>
    <%= f.label "Skein length (yd):" %>
    <%= f.number_field :skein_length, :class => 'text_field', :step => 0.1 %>
  </div>

  <div>
    <%= f.label "Recommended crochet hook:" %>
    <%= f.text_field :hook %>
  </div>

  <div>
    <%= f.label "Recommended knitting needle:" %>
    <%= f.text_field :needle %>
  </div>
</fieldset>

<% if !@brand.id %>
  <br><br>
    <%= f.fields_for :yarns do |y| %>
    <fieldset>
      <legend>Yarn:</legend>
      <div class="field<%= ' field_with_errors' if y.object.errors[:color].any? %>">
        <%= y.label "Color:" %>
        <%= y.text_field :color %><br>
      </div>

      <div>
        <%= y.label "Full skeins:" %>
        <%= y.number_field :count %><br>
      </div>

      <div>
        <%= y.label "Scrap (oz):" %>
        <%= y.text_field :scrap %><br>
      </div>

      <div>
        <%= y.label "Select Brand:" %>
        <%= y.collection_select :brand_id, current_user.brands, :id, :name, {:prompt => "New Brand"} %><br>
      </div>

      <div>
        <%= y.label "Select Project:" %>
        <%= y.collection_select :project_id, current_user.projects, :id, :name %><br>
      </div>
    </fieldset>
    <% end %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/brands/edit.html.erb
<div class="inside">
  <h1>Edit <%= @brand.name %></h1>

  <%= render "form" %>
</div>

app/views/brands/new.html.erb
<div class="inside">
  <h1>Add a Brand</h1>

  <%= render "form" %>
</div>

app/views/brands/show.html.erb
<div class="inside">
  <h1><%= @brand.name %></h1>

  <div class="brand-details">
    <p><b>Material:</b>  <%= @brand.material %></p>
    <p><b>Gauge:</b>  <%= @brand.weight %></p>
    <p><b>Skein size:</b>  <%= @brand.skein_weight %>oz., <%= @brand.skein_length %>yd.</p>
    <p><b>Recommended Hook / Needle:</b>  <%= @brand.hook %>, <%= @brand.needle %></p>
  </div>

  <div class="brand-yarns">
    <h2>Colors of this yarn in your stash:</h2>
    <ul>
      <% @brand.yarns_by_color.each do |yarn| %>
        <li class="each-brand-yarn"><%= link_to yarn.color, edit_yarn_path(yarn) %> <span class="yarn-details"><%= yarn_amount yarn %> <%= list_project yarn %></span></li>
      <% end %>
    </ul>
  </div>

  <%# if current_user.brands.include?(@brand) %>
    <%= button_to "Edit Brand", edit_brand_path(@brand), method: :get %>
    <%= button_to "Delete Brand", { action: "destroy", id: @brand.id }, method: :delete, data: { confirm: "This will delete all associated yarn. Are you sure?" } %>
  <%# end %>
<div>